### ISSUE TITLE
Excuse me, please tell me, what's the different between your two project

### ISSUE THREAD

**Issue by wildfire810** [jonschlinkert/unixify#1]
Excuse me, please tell me, what's the different between your two project
https://github.com/jonschlinkert/unixify
https://github.com/jonschlinkert/normalize-path
Thanks :)

**Comment by doowb** [comment]
`unixify` uses `normalize-path` then does additional things like [removing drive letters and dot-slash](https://github.com/jonschlinkert/unixify#usage).
